ui: mocha-qunit
concurrency: 1
browsers:
    - name: chrome
      version: latest
    - name: firefox
      version: latest
    - name: safari
      version: 9..latest
    - name: iphone
      version: latest
    - name: ie
      version: 9..latest
